...
======================================================================
FAIL: test_count_vowels (__main__.Test_Assn1) (i=11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 25, in test_count_vowels
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '4294967295' != '27'
- 4294967295
+ 27
 : Failed count_vowels(994223116)

======================================================================
FAIL: test_isFib (__main__.Test_Assn1) (i=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in test_isFib
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '0' != '1'
- 0
+ 1
 : Failed isFib(0)

======================================================================
FAIL: test_isFib (__main__.Test_Assn1) (i=2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in test_isFib
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '3' != '4'
- 3
+ 4
 : Failed isFib(2)

======================================================================
FAIL: test_isFib (__main__.Test_Assn1) (i=4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in test_isFib
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '20' != '21'
- 20
+ 21
 : Failed isFib(6765)

======================================================================
FAIL: test_isFib (__main__.Test_Assn1) (i=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in test_isFib
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '26' != '27'
- 26
+ 27
 : Failed isFib(121393)

======================================================================
FAIL: test_isFib (__main__.Test_Assn1) (i=6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 18, in test_isFib
    self.assertEqual(ts[i][1], answers[i], "Failed %s" % ts[i][0])
AssertionError: '44' != '45'
- 44
+ 45
 : Failed isFib(701408733)

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=6)
